# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d00d1117a1b4afc3f1dc0820eba1b07b636a358b388e918d67b39b43105c7c83c2ed2007f5708ad5e95f84d15bdb2c104dc15a64da37b47473065f35b117786a

test:
  secret_key_base: 16e76fe661c2349ca87e9aac7be8f791e4eb2aac591c65c410b9624cc822c3e8d032442e15e20fc5c35d65f9fedcc19fe6fcef40a41241b11604d9310aa9473a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
